In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('run/46650/results_46650.tsv', sep='\t', header=0)
df.head()

                                 ID  k  max_iters            wlhash
0  00063d88244921d6ec46aeab6866a8e2  1          1  1a25f54fd5b1a21e
1  00063d88244921d6ec46aeab6866a8e2  1          2  5820bfa92a7c00ef
2  00063d88244921d6ec46aeab6866a8e2  1          3  06a632d23de0b207
3  00063d88244921d6ec46aeab6866a8e2  1          4  07fba67a0bd0e3db
4  00063d88244921d6ec46aeab6866a8e2  1          5  f35d819a715545e2

In [36]:
(df.query('max_iters==1'))

                                      ID  k  max_iters            wlhash
0       00063d88244921d6ec46aeab6866a8e2  1          1  1a25f54fd5b1a21e
14      00072cf107ae1349c8c59a15c5ce4af1  1          1  0bcfc1810afd6d9e
28      00076733bdbce94d7e44eca84f1425f0  1          1  b46e0fdb8d190ad0
42      000781b7a545fe723159e53127aff659  1          1  fa0820581e17d1ac
56      000a41cdca43be89ed62ea3abf2d0b64  1          1  290732495219c4b9
...                                  ... ..        ...               ...
163240  6010c7b9942d213329827ff47b12ae7f  1          1  b16a811b18f4567f
163254  60135b56870ca88030e1dd175e4b7e9e  1          1  7f9561611566a02c
163268  6014763405d122e81a7d19d30e7cf9bd  1          1  a5b9a260364fb194
163282  6015e2ec69a4d96dd6ec79f0cc8b7975  1          1               NaN
163296  6016e02f8ad70296ed4f239d9af0680b  1          1  df47ec461b7826cd

[11665 rows x 4 columns]

In [25]:
df[(df.duplicated(subset='wlhash'))].sort_values('max_iters')

                                      ID  k  max_iters            wlhash
131866  4d3f18f7c2d5b2119ce34ce17479c30a  1          1  db3c72df915b94c1
163282  6015e2ec69a4d96dd6ec79f0cc8b7975  1          1               NaN
78960   2e786baa11fba80a6a7e9fc32701180f  1          1  5a36297c691f5e72
139860  51e4929accfa3a0e68bff09974c7f0f4  1          1               NaN
152292  5930e00e791767f695dbe8db53658001  1          1               NaN
...                                  ... ..        ...               ...
163281  6014763405d122e81a7d19d30e7cf9bd  1        100  a8b24520b03e539e
163211  600dca51694a6918895721f390d0a7a5  1        100  98f338f551666bb9
78665   2e500b89070fbd46405c5cafd6af17ab  1        100  b62e99e279ecf1b6
27      00072cf107ae1349c8c59a15c5ce4af1  1        100  07300669d9cf4222
163225  600e019587d670331af924e2b463043d  1        100  43c531efb8403f53

[60370 rows x 4 columns]